#!/usr/bin/env python3
import sys
if sys.version_info < (3, 6):
	raise RuntimeError('Python 3.6+ required')

import argparse
import os
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser(add_help = False)
parser.add_argument('-v', '--verbose', action = 'count', default = None, help = 'increase the verbosity level')
parser.add_argument('-q', '--quiet', action = 'store_const', dest = 'verbose', const = 0, help = "don't output verbose information to stderr (clear the verbosity level)")
verbose = 1

args, _ = parser.parse_known_args()
verbosity = args.verbose
if verbosity is None: # Not specified on command-line -- default to 1 unless overridden in environment
	if 'GOT_QUIET' in os.environ:
		verbosity = 0
	elif 'GOT_VERBOSE' in os.environ:
		try:
			verbosity = int(os.environ['GOT_VERBOSE'])
		except ValueError:
			verbosity = 1
	else:
		verbosity = 1

from src.utils import verbose
verbose(set = verbosity)
del verbosity

if __name__ == '__main__':
	rootDir = Path(__file__).parent
	envDir = rootDir / 'venv'
	if 'VIRTUAL_ENV' not in os.environ:
		if not envDir.is_dir():
			print("Creating virtual environment", file = sys.stderr)
			import venv
			venv.create(str(envDir), with_pip = True)

		# activate_this.py is in the project root but expects to be within a virtualenv, so we lie about __file__
		exec((rootDir / 'activate_this.py').read_text(), { '__file__': str(envDir / 'bin' / 'activate_this.py') })

	try:
		from src import dependencies
		if not dependencies.installed:
			print("Installing dependencies", file = sys.stderr)
			subprocess.check_call([ str(envDir / 'bin' / 'pip'), 'install', '-r', str(rootDir / 'requirements.txt') ], stdout = sys.stderr, stderr = sys.stderr)

		from src import main
	except Exception as e:
		print("Fatal error: %s" % e, file = sys.stderr)
		if verbose(2):
			print(file = sys.stderr)
			import traceback
			traceback.print_exc(file = sys.stderr)
		exit(1)
